version: '3.0'
services: 
 vprodb:
  build: 
   context: ./Docker-files/db
  ports: 
   - "3306:3306"
  volumees: 
   - vprodbdata:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=vprodbpass

 
 vprocache01: 
  image: memcached
  ports:
   - "11211:11211"

 vpromq01:
  image: rabbitmq
  ports:
   - "15672:15672"
  environment:
   - RABBIITMQ_DEFAULT_USER=guest
   - RABBITMQ_DEFAULT_PASS=guest
   

 vproapp:
  build:
   context: ./Docker-files/app
  image: vprocontainers/vprofileapp
  container_name: vproapp
  ports: 
   - "8080:8080"
  volumes: 
   - vproappdata:/usr/local/tomcat/webapps 
  
 vproweb:
  build:
   context: ./Docker-files/web
  image: vprocontainers/vprofileweb
  container_name: vproweb
  ports:
   - "80:80"

volumes: 
 vprodbdata: {}
 vproappdata: {} 
